version: '3'
 
services:
  reverseproxy:
    build: .
    container_name: proxyserver_dev
    ports: ["4200:80", "3030", "4220"]
    restart: always
    networks: ["sr_network"]
    external_links:
      - graphql
      - srwa-server

networks:
  sr_network:
    external:
      name: sr_network