version: '3'
 
services:
  reverseproxy:
    build: .
    container_name: proxy_server_prod
    ports: ["4200:80"]
#    restart: always
    networks: ["a_network"]
    external_links:
      - api-server
      - app-server

networks:
  sr_network:
    external:
      name: a_network